import AppKit

/// First‑launch onboarding wizard — walks the user through Accessibility,
/// microphone, speech‑recognition, and Claude CLI permissions.
final class OnboardingWindow: NSObject {

    private var window: NSWindow?
    private var config: Config
    private var onComplete: (Config) -> Void

    private let steps: [(title: String, symbol: String, body: String)] = [
        ("Accessibility", "accessibility",
         "Smriti reads the focused window to capture context. Click \"Open System Settings\" to grant Accessibility permission, then return here."),
        ("Microphone", "mic",
         "Voice notes and meeting recordings need microphone access. Click \"Allow\" when macOS prompts you."),
        ("Speech Recognition", "waveform",
         "Transcription happens on‑device using Apple Speech. Click \"Allow\" when prompted."),
        ("Claude CLI", "terminal",
         "Chronicles are generated by the Claude CLI. Install it from https://claude.ai/code if you haven't already."),
    ]

    private var currentStep = 0
    private let stack = NSStackView()
    private let titleLabel = NSTextField(labelWithString: "")
    private let bodyLabel = NSTextField(labelWithString: "")
    private let iconView = NSImageView()
    private let nextButton = ThemedButton()
    private let skipButton = NSButton()
    private let pageDots = NSStackView()

    init(config: Config, onComplete: @escaping (Config) -> Void) {
        self.config = config
        self.onComplete = onComplete
        super.init()
    }

    func show() {
        let w = NSWindow(
            contentRect: NSRect(x: 0, y: 0, width: 480, height: 360),
            styleMask: [.titled, .closable],
            backing: .buffered, defer: false)
        w.title = "Welcome to Smriti"
        w.isReleasedWhenClosed = false
        w.center()

        let contentView = ThemedView(frame: w.contentView!.bounds)
        contentView.autoresizingMask = [.width, .height]
        contentView.fillColor = Theme.surface
        w.contentView = contentView

        stack.orientation = .vertical
        stack.alignment = .centerX
        stack.spacing = 16
        stack.translatesAutoresizingMaskIntoConstraints = false
        contentView.addSubview(stack)
        NSLayoutConstraint.activate([
            stack.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 32),
            stack.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -32),
            stack.centerYAnchor.constraint(equalTo: contentView.centerYAnchor, constant: -20),
        ])

        iconView.image = NSImage(systemSymbolName: steps[0].symbol, accessibilityDescription: nil)
        iconView.contentTintColor = Theme.accent
        iconView.widthAnchor.constraint(equalToConstant: 48).isActive = true
        iconView.heightAnchor.constraint(equalToConstant: 48).isActive = true
        stack.addArrangedSubview(iconView)

        titleLabel.font = Theme.body()
        titleLabel.textColor = Theme.ink
        titleLabel.alignment = .center
        titleLabel.maximumNumberOfLines = 0
        stack.addArrangedSubview(titleLabel)

        bodyLabel.font = Theme.body(12)
        bodyLabel.textColor = Theme.inkSecondary
        bodyLabel.alignment = .center
        bodyLabel.maximumNumberOfLines = 0
        bodyLabel.preferredMaxLayoutWidth = 400
        stack.addArrangedSubview(bodyLabel)

        // Page dots
        for i in 0..<steps.count {
            let dot = NSView()
            dot.wantsLayer = true
            dot.layer?.cornerRadius = 4
            dot.widthAnchor.constraint(equalToConstant: 8).isActive = true
            dot.heightAnchor.constraint(equalToConstant: 8).isActive = true
            dot.layer?.backgroundColor = (i == 0 ? Theme.accent : Theme.inkTertiary).cgColor
            pageDots.addArrangedSubview(dot)
        }
        pageDots.spacing = 6
        pageDots.translatesAutoresizingMaskIntoConstraints = false
        contentView.addSubview(pageDots)
        NSLayoutConstraint.activate([
            pageDots.centerXAnchor.constraint(equalTo: contentView.centerXAnchor),
            pageDots.topAnchor.constraint(equalTo: stack.bottomAnchor, constant: 24),
        ])

        // Buttons
        let buttonRow = NSStackView()
        buttonRow.spacing = 12
        buttonRow.translatesAutoresizingMaskIntoConstraints = false
        contentView.addSubview(buttonRow)
        NSLayoutConstraint.activate([
            buttonRow.centerXAnchor.constraint(equalTo: contentView.centerXAnchor),
            buttonRow.topAnchor.constraint(equalTo: pageDots.bottomAnchor, constant: 24),
        ])

        nextButton.title = "Continue"
        nextButton.bezelStyle = .rounded
        nextButton.font = Theme.body()
        nextButton.target = self
        nextButton.action = #selector(nextClicked)
        nextButton.widthAnchor.constraint(equalToConstant: 120).isActive = true
        buttonRow.addArrangedSubview(nextButton)

        skipButton.title = "Skip All"
        skipButton.bezelStyle = .inline
        skipButton.font = Theme.body(12)
        skipButton.target = self
        skipButton.action = #selector(skipClicked)
        buttonRow.addArrangedSubview(skipButton)

        window = w
        updateStep()
        w.makeKeyAndOrderFront(nil)
    }

    private func updateStep() {
        let step = steps[currentStep]
        titleLabel.stringValue = "Step \(currentStep + 1) of \(steps.count): \(step.title)"
        bodyLabel.stringValue = step.body
        iconView.image = NSImage(systemSymbolName: step.symbol, accessibilityDescription: nil)
        nextButton.title = currentStep == steps.count - 1 ? "Get Started" : "Continue"

        // Update dots
        if let dots = pageDots.arrangedSubviews as? [NSView] {
            for (i, dot) in dots.enumerated() {
                dot.layer?.backgroundColor = (i == currentStep ? Theme.accent : Theme.inkTertiary).cgColor
            }
        }

        // Prompt for current permission
        switch currentStep {
        case 0: AXReader.ensureAccessibilityPermission()
        case 1: Transcriber.requestAuthorization()
        case 2: Transcriber.requestAuthorization()
        default: break
        }
    }

    @objc private func nextClicked() {
        if currentStep < steps.count - 1 {
            currentStep += 1
            updateStep()
        } else {
            finish()
        }
    }

    @objc private func skipClicked() {
        finish()
    }

    private func finish() {
        config.hasCompletedOnboarding = true
        try? config.save()
        window?.close()
        window = nil
        onComplete(config)
    }
}
